const $=id=>document.getElementById(id);let roomList=[],result={all:[],mutual:[],onlyMe:[],fansOnly:[],neither:[]},currentTab="all",currentGroup=0,installPrompt=null,adminLoggedIn=false,matchLocked=false;let config={sheetId:"",sheetName:"Sheet1",fallbackCsv:"room-list.csv",adminPassword:"0702"};
function toast(m){const e=$("toast");e.textContent=m;e.style.display="block";clearTimeout(toast.t);toast.t=setTimeout(()=>e.style.display="none",1800)}
function normalize(v){return String(v||"").trim().toLowerCase().replace(/^https?:\/\/(www\.)?instagram\.com\//,"").replace(/^instagram\.com\//,"").replace(/^_u\//,"").replace(/^@+/,"").replace(/[?#].*$/,"").replace(/\/+$/,"").trim()}
function validUsername(v){return /^[a-z0-9._]{1,30}$/.test(v)&&!["instagram","accounts","explore","direct","p","reels","stories","www","about","privacy","terms","login","_u"].includes(v)}
function unique(a){const s=new Set();for(const v of a||[]){const id=normalize(v);if(validUsername(id))s.add(id)}return[...s]}
function parseCsv(t){const rows=[];let r=[],c="",q=false;for(let i=0;i<t.length;i++){const ch=t[i],n=t[i+1];if(ch==='"'&&q&&n==='"'){c+='"';i++;continue}if(ch==='"'){q=!q;continue}if(ch===','&&!q){r.push(c);c="";continue}if((ch==='\n'||ch==='\r')&&!q){if(c||r.length){r.push(c);rows.push(r);r=[];c=""}if(ch==='\r'&&n==='\n')i++;continue}c+=ch}if(c||r.length){r.push(c);rows.push(r)}return rows}
function rowsToRoom(rows){const list=[];rows.forEach((r,i)=>{const joined=r.join(" ");if(i===0&&(joined.includes("번호")||joined.includes("닉네임")||joined.includes("아이디")))return;const id=normalize(r[2]||r[1]||r[0]);if(validUsername(id))list.push({no:r[0]||list.length+1,name:r[1]||"",id})});const seen=new Set();return list.filter(x=>!seen.has(x.id)&&seen.add(x.id))}
async function loadConfig(){try{const r=await fetch(`config.json?t=${Date.now()}`,{cache:"no-store"});if(r.ok)config={...config,...await r.json()}}catch{}}
function sheetUrl(){return `https://docs.google.com/spreadsheets/d/${config.sheetId}/edit`}
async function loadRoomList(show=false){setSheetState("불러오는 중");const urls=[];if(config.sheetId){const s=encodeURIComponent(config.sheetName||"Sheet1");urls.push(`https://docs.google.com/spreadsheets/d/${config.sheetId}/gviz/tq?tqx=out:csv&sheet=${s}&t=${Date.now()}`);urls.push(`https://docs.google.com/spreadsheets/d/${config.sheetId}/export?format=csv&sheet=${s}&t=${Date.now()}`)}urls.push(`${config.fallbackCsv||"room-list.csv"}?t=${Date.now()}`);let err="";for(const u of urls){try{const r=await fetch(u,{cache:"no-store"});if(!r.ok)throw Error(`HTTP ${r.status}`);const list=rowsToRoom(parseCsv(await r.text()));if(!list.length)throw Error("0명");roomList=list;setSheetState("정상");updateFollowStats();renderGroupTabs();renderFollowList();if(show)toast("명단 새로고침 완료");return}catch(e){err=e.message}}setSheetState("오류");$("followState").textContent=`명단을 불러오지 못했습니다. (${err})`;if(show)toast("명단 불러오기 실패")}
function setSheetState(s){if($("roomState"))$("roomState").textContent=s==="정상"?`${roomList.length}명 준비 완료`:s;if($("adminSheetState"))$("adminSheetState").textContent=s}
function updateFollowStats(){const groups=Math.ceil(roomList.length/500);$("followTotal").textContent=`${roomList.length}명`;$("groupTotal").textContent=`${groups}조`;$("lastRefresh").textContent=new Date().toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit"});$("adminTotal").textContent=`${roomList.length}명`;$("adminGroups").textContent=`${groups}조`;$("followState").textContent=`전체 ${roomList.length}명 · 500명씩 ${groups}개 조`}
function renderGroupTabs(){const total=Math.max(1,Math.ceil(roomList.length/500));$("groupTabs").innerHTML=['전체',...Array.from({length:total},(_,i)=>`${i+1}조`)].map((t,i)=>`<button class="group-tab ${i===currentGroup?'active':''}" data-group="${i}">${t}</button>`).join("");document.querySelectorAll(".group-tab").forEach(b=>b.onclick=()=>{currentGroup=Number(b.dataset.group);renderGroupTabs();renderFollowList()})}
function followFiltered(){const q=String($("followSearch").value||"").trim().toLowerCase();let a=roomList;if(currentGroup>0)a=a.slice((currentGroup-1)*500,currentGroup*500);return q?a.filter(x=>String(x.no).includes(q)||x.id.includes(normalize(q))||String(x.name).toLowerCase().includes(q)):a}
function renderFollowList(){const a=followFiltered();$("followList").innerHTML=a.length?a.map(x=>`<div class="follow-item"><span>${escapeHtml(x.no)}</span><span>${escapeHtml(x.name)}</span><a href="https://www.instagram.com/${encodeURIComponent(x.id)}/" target="_blank" rel="noopener">@${escapeHtml(x.id)}</a><a class="insta-btn" href="https://www.instagram.com/${encodeURIComponent(x.id)}/" target="_blank" rel="noopener">인스타</a></div>`).join(""):'<div class="empty-state">검색 결과가 없습니다.</div>'}
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'})}
function findFiles(zip){const f=Object.keys(zip.files).filter(p=>!zip.files[p].dir);return{followers:f.filter(p=>/followers_\d+\.(html|json)$/i.test(p.replace(/\\/g,"/").split("/").pop())),following:f.find(p=>/^following\.(html|json)$/i.test(p.replace(/\\/g,"/").split("/").pop()))}}
function extractHtml(t){const ids=[];let m,r=/href=["']https?:\/\/(?:www\.)?instagram\.com\/(?:_u\/)?([A-Za-z0-9._]+)\/?[^"']*["']/gi;while((m=r.exec(t)))ids.push(m[1]);if(!ids.length){r=/https?:\/\/(?:www\.)?instagram\.com\/(?:_u\/)?([A-Za-z0-9._]+)/gi;while((m=r.exec(t)))ids.push(m[1])}return unique(ids)}
function walkJson(v,o){if(v==null)return;if(typeof v==='string'){const id=normalize(v);if(validUsername(id))o.push(id);return}if(Array.isArray(v)){v.forEach(x=>walkJson(x,o));return}if(typeof v==='object')Object.values(v).forEach(x=>walkJson(x,o))}
function extractJson(t){const o=[];try{walkJson(JSON.parse(t),o)}catch{}return unique(o)}
async function parseInstagramZip(file){if(!file)throw Error("ZIP 파일을 선택해 주세요.");if(!window.JSZip)throw Error("ZIP 분석 라이브러리를 불러오지 못했습니다.");const z=await JSZip.loadAsync(file),p=findFiles(z);if(!p.followers.length)throw Error("followers_1 파일을 찾지 못했습니다.");if(!p.following)throw Error("following 파일을 찾지 못했습니다.");let followers=[];for(const path of p.followers){const t=await z.files[path].async("string");followers.push(...(path.endsWith('.json')?extractJson(t):extractHtml(t)))}const gt=await z.files[p.following].async("string"),following=p.following.endsWith('.json')?extractJson(gt):extractHtml(gt);return{followers:unique(followers),following}}
function classify(followers,following){const F=new Set(followers),G=new Set(following),all=roomList.map(p=>({...p,status:F.has(p.id)&&G.has(p.id)?'mutual':!F.has(p.id)&&G.has(p.id)?'onlyMe':F.has(p.id)&&!G.has(p.id)?'fansOnly':'neither'}));result={all,mutual:all.filter(x=>x.status==='mutual'),onlyMe:all.filter(x=>x.status==='onlyMe'),fansOnly:all.filter(x=>x.status==='fansOnly'),neither:all.filter(x=>x.status==='neither')}}
async function analyze(){if(matchLocked){toast("현재 맞팔확인 기능이 잠겨 있습니다.");return}const b=$("analyzeBtn");try{b.disabled=true;b.textContent="분석 중...";if(!roomList.length)await loadRoomList();const p=await parseInstagramZip($("zipFile").files[0]);classify(p.followers,p.following);updateSummary();showTab('all');$("summarySection").classList.remove('hidden');$("resultsSection").classList.remove('hidden');$("status").textContent=`분석 완료 · 단톡방 ${roomList.length}명 기준`;toast("분석 완료")}catch(e){$("status").textContent=`오류: ${e.message}`;toast("분석 실패")}finally{b.disabled=false;b.innerHTML='맞팔 분석 시작 <span>→</span>'}}
function pct(n,t){return t?`${((n/t)*100).toFixed(1)}%`:'0%'}function updateSummary(){const t=result.all.length;for(const k of ['mutual','onlyMe','fansOnly','neither']){$(`${k}Count`).textContent=`${result[k].length}명`;$(`${k}Rate`).textContent=pct(result[k].length,t);$(`tab${k[0].toUpperCase()+k.slice(1)}`).textContent=result[k].length}$("tabAll").textContent=t;$("rateText").innerHTML=`단톡방 맞팔률 <strong>${pct(result.mutual.length,t)}</strong> · ${result.mutual.length}/${t}명`}
function label(s){return{mutual:'맞팔 완료',onlyMe:'나만 팔로우 함',fansOnly:'상대가 팔로우만 함',neither:'서로 팔로우 안 함'}[s]}
function showTab(t){currentTab=t;document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));renderMatchList()}
function matchFiltered(){const q=String($("searchInput").value||'').trim().toLowerCase(),a=result[currentTab]||[];return q?a.filter(x=>x.id.includes(normalize(q))||String(x.name).toLowerCase().includes(q)):a}
function renderMatchList(){const a=matchFiltered();$("list").innerHTML=a.length?a.map((x,i)=>`<div class="item"><span class="item-no">${i+1}</span><div class="item-person"><strong class="item-name">${escapeHtml(x.name)}</strong><a class="id" href="https://www.instagram.com/${encodeURIComponent(x.id)}/" target="_blank" rel="noopener">@${escapeHtml(x.id)}</a></div><span class="badge ${x.status}">${label(x.status)}</span><a class="insta" href="https://www.instagram.com/${encodeURIComponent(x.id)}/" target="_blank" rel="noopener">인스타</a></div>`).join(''):'<div class="empty-state">결과가 없습니다.</div>'}
async function copyCurrent(){const a=currentTab==='all'?[...result.onlyMe,...result.neither]:matchFiltered();if(!a.length)return toast('복사할 명단이 없습니다.');await navigator.clipboard.writeText(a.map((x,i)=>`${i+1}. ${x.name} @${x.id} - ${label(x.status)}`).join('\n'));toast('복사 완료')}
function downloadCsv(){const a=matchFiltered();if(!a.length)return toast('다운로드할 명단이 없습니다.');const rows=[["번호","닉네임","아이디","상태"],...a.map((x,i)=>[i+1,x.name,`@${x.id}`,label(x.status)])],csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\r\n'),u=URL.createObjectURL(new Blob([csv],{type:'text/csv'})),el=document.createElement('a');el.href=u;el.download='여우방_명단.csv';el.click();URL.revokeObjectURL(u)}
function reset(){$("zipFile").value='';$("fileName").textContent='인스타그램 ZIP 파일 선택';$("summarySection").classList.add('hidden');$("resultsSection").classList.add('hidden')}
function notices(){try{return JSON.parse(localStorage.getItem('yb_notices')||'[]')}catch{return[]}}
function saveNotices(a){localStorage.setItem('yb_notices',JSON.stringify(a));renderNotices()}
function renderNotices(){const a=notices();$("adminNotices").textContent=`${a.length}개`;$("noticeCard").classList.toggle('hidden',!a.length);$("noticeList").innerHTML=a.map(n=>`<div class="notice-item"><h4>${escapeHtml(n.title)}</h4><p>${escapeHtml(n.body)}</p></div>`).join('');$("adminNoticeList").innerHTML=a.length?a.map((n,i)=>`<div class="notice-row"><div><strong>${escapeHtml(n.title)}</strong><div class="subtext">${escapeHtml(n.body)}</div></div><button data-del="${i}">삭제</button></div>`).join(''):'<p class="state-text">등록된 공지가 없습니다.</p>';document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{const x=notices();x.splice(Number(b.dataset.del),1);saveNotices(x);toast('공지 삭제 완료')})}
function adminLogin(){if($("adminPassword").value===String(config.adminPassword||'0702')){adminLoggedIn=true;$("adminPanel").classList.remove('hidden');$("adminLoginCard").classList.add('hidden');renderNotices();toast('운영진 로그인 완료')}else{$("adminLoginMsg").textContent='비밀번호가 다릅니다.';toast('로그인 실패')}}
function adminLogout(){adminLoggedIn=false;$("adminPanel").classList.add('hidden');$("adminLoginCard").classList.remove('hidden');$("adminPassword").value=''}
function saveNotice(){const title=$("noticeTitle").value.trim(),body=$("noticeBody").value.trim();if(!title||!body)return toast('제목과 내용을 입력해 주세요.');const a=notices();a.unshift({title,body,createdAt:new Date().toISOString()});saveNotices(a);$("noticeTitle").value='';$("noticeBody").value='';toast('공지 저장 완료')}

function loadMatchLock(){
  matchLocked=localStorage.getItem('yb_match_locked')==='1';
  applyMatchLock();
}
function applyMatchLock(){
  const lockCard=$("matchLockCard"),content=$("matchContent"),state=$("matchLockState");
  if(lockCard)lockCard.classList.toggle('hidden',!matchLocked);
  if(content)content.classList.toggle('hidden',matchLocked);
  if(state){
    state.textContent=matchLocked?'잠금 중':'사용 가능';
    state.classList.toggle('locked',matchLocked);
    state.classList.toggle('unlocked',!matchLocked);
  }
}
function setMatchLock(locked){
  matchLocked=Boolean(locked);
  localStorage.setItem('yb_match_locked',matchLocked?'1':'0');
  applyMatchLock();
  if(matchLocked){
    reset();
    toast('맞팔확인 기능을 잠갔습니다.');
  }else{
    toast('맞팔확인 잠금을 해제했습니다.');
  }
}

function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>showView(b.dataset.view));$("followSearch").oninput=renderFollowList;$("refreshFollowBtn").onclick=()=>loadRoomList(true);$("reloadRoomBtn").onclick=()=>loadRoomList(true);$("zipFile").onchange=()=>$("fileName").textContent=$("zipFile").files[0]?.name||'인스타그램 ZIP 파일 선택';$("analyzeBtn").onclick=analyze;$("resetBtn").onclick=reset;$("searchInput").oninput=renderMatchList;$("copyBtn").onclick=copyCurrent;$("csvBtn").onclick=downloadCsv;document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));$("adminLoginBtn").onclick=adminLogin;$("adminPassword").onkeydown=e=>{if(e.key==='Enter')adminLogin()};$("adminLogoutBtn").onclick=adminLogout;$("openSheetBtn").onclick=()=>window.open(sheetUrl(),'_blank');$("adminRefreshBtn").onclick=()=>loadRoomList(true);$("saveNoticeBtn").onclick=saveNotice;$("lockMatchBtn").onclick=()=>setMatchLock(true);$("unlockMatchBtn").onclick=()=>setMatchLock(false);$("closeNoticeBtn").onclick=()=>$("noticeCard").classList.add('hidden');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e});$("installBtn").onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null}else toast('브라우저 메뉴에서 홈 화면에 추가를 눌러주세요.')};window.addEventListener('DOMContentLoaded',async()=>{await loadConfig();loadMatchLock();await loadRoomList();renderNotices();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js?v=190').catch(()=>{})});